const shopReviewsData = {
  shop1: {
    reviews: [
      {
        author: "Jan Kowalski",
        date: "05.09.2023",
        content: "Bardzo dobre warzywa!",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [
          "https://picsum.photos/400/400?random=1",
          "https://picsum.photos/400/400?random=2",
          "https://picsum.photos/400/400?random=3",
          "https://picsum.photos/400/400?random=4",
          "https://picsum.photos/400/400?random=5",
          "https://picsum.photos/400/400?random=6",
          "https://picsum.photos/400/400?random=7",
          "https://picsum.photos/400/400?random=8",
          "https://picsum.photos/400/400?random=9",
        ],
        rating: 5,
        thumbsUp: 23,
        thumbsDown: 2,
      },
      {
        author: "Anna Nowak",
        date: "03.09.2023",
        content:
          "Miła obsługa, ale trochę drogo.Miła obsługa, ale trochę drogo.Miła obsługa, ale trochę drogo.Miła obsługa, ale trochę drogo.Miła obsługa, ale trochę drogo.Miła obsługa, ale trochę drogo.Miła obsługa, ale trochę drogo.",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
        ],
        rating: 4,
        thumbsUp: 10,
        thumbsDown: 5,
      },
      {
        author: "Jan Kowalski",
        date: "05.09.2023",
        content: "Bardzo dobre warzywa!",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
        ],
        rating: 3,
        thumbsUp: 23,
        thumbsDown: 2,
      },
      {
        author: "Anna Nowak",
        date: "03.09.2023",
        content: "Miła obsługa, ale trochę drogo.",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: ["https://picsum.photos/400/400"],
        rating: 2,
        thumbsUp: 10,
        thumbsDown: 5,
      },
      {
        author: "Marta Kaczmarek",
        date: "10.08.2023",
        content: "Świetne miejsce na zakupy, zawsze świeże produkty.",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [],
        rating: 1,
        thumbsUp: 18,
        thumbsDown: 1,
      },
      {
        author: "Tomasz Nowicki",
        date: "27.07.2023",
        content: "Duży wybór, konkurencyjne ceny.",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
        ],
        rating: 0,
        thumbsUp: 12,
        thumbsDown: 0,
      },
      {
        author: "Jan Kowalski",
        date: "05.09.2023",
        content: "Bardzo dobre warzywa!",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
        ],
        rating: 5,
        thumbsUp: 23,
        thumbsDown: 2,
      },
    ],
  },
  shop2: {
    reviews: [
      {
        author: "Jan Kowalski",
        date: "05.09.2023",
        content: "Bardzo dobre warzywa!",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
        ],
        rating: 5,
        thumbsUp: 23,
        thumbsDown: 2,
      },
      {
        author: "Anna Nowak",
        date: "03.09.2023",
        content: "Miła obsługa, ale trochę drogo.",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
        ],
        rating: 3,
        thumbsUp: 10,
        thumbsDown: 5,
      },
      {
        author: "Jan Kowalski",
        date: "05.09.2023",
        content: "Bardzo dobre warzywa!",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
        ],
        rating: 5,
        thumbsUp: 23,
        thumbsDown: 2,
      },
      {
        author: "Anna Nowak",
        date: "03.09.2023",
        content: "Miła obsługa, ale trochę drogo.",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
        ],
        rating: 3,
        thumbsUp: 10,
        thumbsDown: 5,
      },
      {
        author: "Marta Kaczmarek",
        date: "10.08.2023",
        content: "Świetne miejsce na zakupy, zawsze świeże produkty.",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: ["https://picsum.photos/400/400"],
        rating: 4,
        thumbsUp: 18,
        thumbsDown: 1,
      },
      {
        author: "Tomasz Nowicki",
        date: "27.07.2023",
        content: "Duży wybór, konkurencyjne ceny.",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [],
        rating: 4,
        thumbsUp: 12,
        thumbsDown: 0,
      },
    ],
  },
  shop3: {
    reviews: [
      {
        author: "Jan Kowalski",
        date: "05.09.2023",
        content: "Bardzo dobre warzywa!",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
        ],
        rating: 5,
        thumbsUp: 23,
        thumbsDown: 2,
      },
      {
        author: "Anna Nowak",
        date: "03.09.2023",
        content: "Miła obsługa, ale trochę drogo.",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
        ],
        rating: 3,
        thumbsUp: 10,
        thumbsDown: 5,
      },
      {
        author: "Jan Kowalski",
        date: "05.09.2023",
        content: "Bardzo dobre warzywa!",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
        ],
        rating: 5,
        thumbsUp: 23,
        thumbsDown: 2,
      },
      {
        author: "Anna Nowak",
        date: "03.09.2023",
        content: "Miła obsługa, ale trochę drogo.",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
        ],
        rating: 3,
        thumbsUp: 10,
        thumbsDown: 5,
      },
      {
        author: "Marta Kaczmarek",
        date: "10.08.2023",
        content: "Świetne miejsce na zakupy, zawsze świeże produkty.",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
        ],
        rating: 4,
        thumbsUp: 18,
        thumbsDown: 1,
      },
      {
        author: "Tomasz Nowicki",
        date: "27.07.2023",
        content: "Duży wybór, konkurencyjne ceny.",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
        ],
        rating: 4,
        thumbsUp: 12,
        thumbsDown: 0,
      },
    ],
  },
  shop4: {
    reviews: [
      {
        author: "Jan Kowalski",
        date: "05.09.2023",
        content: "Bardzo dobre warzywa!",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
        ],
        rating: 5,
        thumbsUp: 23,
        thumbsDown: 2,
      },
      {
        author: "Anna Nowak",
        date: "03.09.2023",
        content: "Miła obsługa, ale trochę drogo.",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
        ],
        rating: 3,
        thumbsUp: 10,
        thumbsDown: 5,
      },
      {
        author: "Jan Kowalski",
        date: "05.09.2023",
        content: "Bardzo dobre warzywa!",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
        ],
        rating: 5,
        thumbsUp: 23,
        thumbsDown: 2,
      },
      {
        author: "Anna Nowak",
        date: "03.09.2023",
        content: "Miła obsługa, ale trochę drogo.",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
        ],
        rating: 3,
        thumbsUp: 10,
        thumbsDown: 5,
      },
      {
        author: "Marta Kaczmarek",
        date: "10.08.2023",
        content: "Świetne miejsce na zakupy, zawsze świeże produkty.",
        reviewImages: [
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
        ],
        profileImage: "https://picsum.photos/400/400",
        rating: 4,
        thumbsUp: 18,
        thumbsDown: 1,
      },
      {
        author: "Tomasz Nowicki",
        date: "27.07.2023",
        content: "Duży wybór, konkurencyjne ceny.",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
        ],
        rating: 4,
        thumbsUp: 12,
        thumbsDown: 0,
      },
    ],
  },
  shop5: {
    reviews: [
      {
        author: "Jan Kowalski",
        date: "05.09.2023",
        content: "Bardzo dobre warzywa!",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
        ],
        rating: 5,
        thumbsUp: 23,
        thumbsDown: 2,
      },
      {
        author: "Anna Nowak",
        date: "03.09.2023",
        content: "Miła obsługa, ale trochę drogo.",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
        ],
        rating: 3,
        thumbsUp: 10,
        thumbsDown: 5,
      },
      {
        author: "Jan Kowalski",
        date: "05.09.2023",
        content: "Bardzo dobre warzywa!",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
        ],
        rating: 5,
        thumbsUp: 23,
        thumbsDown: 2,
      },
      {
        author: "Anna Nowak",
        date: "03.09.2023",
        content: "Miła obsługa, ale trochę drogo.",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
        ],
        rating: 3,
        thumbsUp: 10,
        thumbsDown: 5,
      },
      {
        author: "Marta Kaczmarek",
        date: "10.08.2023",
        content: "Świetne miejsce na zakupy, zawsze świeże produkty.",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
        ],
        rating: 4,
        thumbsUp: 18,
        thumbsDown: 1,
      },
      {
        author: "Tomasz Nowicki",
        date: "27.07.2023",
        content: "Duży wybór, konkurencyjne ceny.",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
        ],
        rating: 4,
        thumbsUp: 12,
        thumbsDown: 0,
      },
    ],
  },
  shop6: {
    reviews: [
      {
        author: "Jan Kowalski",
        date: "05.09.2023",
        content: "Bardzo dobre warzywa!",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
        ],
        rating: 5,
        thumbsUp: 23,
        thumbsDown: 2,
      },
      {
        author: "Anna Nowak",
        date: "03.09.2023",
        content: "Miła obsługa, ale trochę drogo.",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
        ],
        rating: 3,
        thumbsUp: 10,
        thumbsDown: 5,
      },
      {
        author: "Jan Kowalski",
        date: "05.09.2023",
        content: "Bardzo dobre warzywa!",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
        ],
        rating: 5,
        thumbsUp: 23,
        thumbsDown: 2,
      },
      {
        author: "Anna Nowak",
        date: "03.09.2023",
        content: "Miła obsługa, ale trochę drogo.",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
        ],
        rating: 3,
        thumbsUp: 10,
        thumbsDown: 5,
      },
      {
        author: "Marta Kaczmarek",
        date: "10.08.2023",
        content: "Świetne miejsce na zakupy, zawsze świeże produkty.",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
        ],
        rating: 4,
        thumbsUp: 18,
        thumbsDown: 1,
      },
      {
        author: "Tomasz Nowicki",
        date: "27.07.2023",
        content: "Duży wybór, konkurencyjne ceny.",
        profileImage: "https://picsum.photos/400/400",
        reviewImages: [
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
          "https://picsum.photos/400/400",
        ],
        rating: 4,
        thumbsUp: 12,
        thumbsDown: 0,
      },
    ],
  },
};

export default shopReviewsData;
